// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TecPay.Catalog.Infrastructure;

#nullable disable

namespace TecPay.Catalog.Infrastructure._MigracionesSqlite
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("TecPay.Catalog.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoriaNombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaBajaUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("TecPay.Catalog.Domain.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FK_IDCategoria")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaBajaUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductoDescripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductoPrecio")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductoSKU")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoStock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FK_IDCategoria");

                    b.HasIndex("ProductoSKU")
                        .IsUnique();

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("TecPay.Catalog.Domain.Entities.Producto", b =>
                {
                    b.HasOne("TecPay.Catalog.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Col_Producto")
                        .HasForeignKey("FK_IDCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TecPay.Catalog.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Col_Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
